### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by aalistarh** [yummykwok/Libnfc-Embedded#1]
Hi there, 
I would be interested to try your code, but does it work on a known dev kit? 
Thank you.

**Comment by yummykwok** [comment]
Hi aalistarh, it works on STM32F107.
Simply change the UART interface in the file _libnfc/buses/stm32_f107_uart.c_ if you want to port to other platforms.

**Comment by aalistarh** [comment]
Thank you. I will try it.
